### ISSUE TITLE
wss websocket pass query parameters problem

### ISSUE THREAD

**Issue by muralid9** [gorilla/.github#5]
**Describe the problem you're having**
> A clear and concise description of what the bug is.
Cannot pass query parameters with ? Is that a limitation from the application or am I doing any thin

**Versions**
> Go version: `go version`

> package version: run `git rev-parse HEAD` inside the repo

…

**"Show me the code!"**
> A minimal code snippet can be useful, otherwise we're left guessing!

> Hint: wrap it with backticks to format it

…

**Comment by elithrar** [comment]
This isn’t the right place for WebSocket issues. Please open them on gorilla/websocket
